# Generated by Django 4.1.1 on 2023-04-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='subcounty',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='town',
        ),
    ]
